version: "3"

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
      args:
        IMAGE_NAME: "gourav094/task-manager:latest"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data:
  jenkins-data:
